package circuit.ru.xmn.circuit.model.presets

import circuit.ru.xmn.circuit.model.midicontrol.MidiControlType
import circuit.ru.xmn.circuit.model.midicontrol.MidiHandler
import circuit.ru.xmn.circuit.model.midicontrol.NrpnValue
import circuit.ru.xmn.circuit.model.midicontrol.Range

object CircuitSynthProvider {

    fun provideCircuitSynth(sendMessage: (ByteArray) -> Unit): SynthMidiController {
        return SynthMidiController(
                provideControls(), sendMessage)
    }

    private fun provideControls(): List<MidiHandler> {
        return (synth(1)
                + synth(2)
                + listOf(
                //drum control
                MidiHandler("drum 1 patch select", 10, 8, range = Range(0, 63)),
                MidiHandler("drum 1 level", 10, 12),
                MidiHandler("drum 1 pitch", 10, 14),
                MidiHandler("drum 1 decay", 10, 15),
                MidiHandler("drum 1 distortion", 10, 16),
                MidiHandler("drum 1 EQ", 10, 17),
                MidiHandler("drum 1 pan", 10, 77),
                MidiHandler("drum 2 patch select", 10, 18, range = Range(0, 63)),
                MidiHandler("drum 2 level", 10, 23),
                MidiHandler("drum 2 pitch", 10, 34),
                MidiHandler("drum 2 decay", 10, 40),
                MidiHandler("drum 2 distortion", 10, 42),
                MidiHandler("drum 2 EQ", 10, 43),
                MidiHandler("drum 2 pan", 10, 78),
                MidiHandler("drum 3 patch select", 10, 44, range = Range(0, 63)),
                MidiHandler("drum 3 level", 10, 45),
                MidiHandler("drum 3 pitch", 10, 46),
                MidiHandler("drum 3 decay", 10, 47),
                MidiHandler("drum 3 distortion", 10, 48),
                MidiHandler("drum 3 EQ", 10, 49),
                MidiHandler("drum 3 pan", 10, 79),
                MidiHandler("drum 4 patch select", 10, 50, range = Range(0, 63)),
                MidiHandler("drum 4 level", 10, 53),
                MidiHandler("drum 4 pitch", 10, 55),
                MidiHandler("drum 4 decay", 10, 57),
                MidiHandler("drum 4 distortion", 10, 61),
                MidiHandler("drum 4 EQ", 10, 76),
                MidiHandler("drum 4 pan", 10, 80),

                //session control
                //Reverb
                MidiHandler("reverb synth 1 send level", 16, 88),
                MidiHandler("reverb synth 2 send level", 16, 89),
                MidiHandler("reverb drum 1 send level", 16, 90),
                MidiHandler("reverb drum 2 send level", 16, 106),
                MidiHandler("reverb drum 3 send level", 16, 109),
                MidiHandler("reverb drum 4 send level", 16, 110),
                MidiHandler("type", 16, NrpnValue(1, 18).value(), range = Range(0, 5), controlType = MidiControlType.NRPN),
                MidiHandler("decay", 16, NrpnValue(1, 19).value(), controlType = MidiControlType.NRPN),
                MidiHandler("damping", 16, NrpnValue(1, 20).value(), controlType = MidiControlType.NRPN),
                //Delay
                MidiHandler("delay synth 1 send level", 16, 111),
                MidiHandler("delay synth 2 send level", 16, 112),
                MidiHandler("delay drum 1 send level", 16, 113),
                MidiHandler("delay drum 2 send level", 16, 114),
                MidiHandler("delay drum 3 send level", 16, 115),
                MidiHandler("delay drum 4 send level", 16, 116),
                MidiHandler("time", 16, NrpnValue(1, 6).value(), controlType = MidiControlType.NRPN),
                MidiHandler("time sync", 16, NrpnValue(1, 7).value(), range = Range(0, 35), controlType = MidiControlType.NRPN),
                MidiHandler("feedback", 16, NrpnValue(1, 8).value(), controlType = MidiControlType.NRPN),
                MidiHandler("width", 16, NrpnValue(1, 9).value(), controlType = MidiControlType.NRPN),
                MidiHandler("left-right ratio", 16, NrpnValue(1, 10).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("slew rate", 16, NrpnValue(1, 11).value(), controlType = MidiControlType.NRPN),
                //Master Filter
                MidiHandler("frequency", 16, 74),
                MidiHandler("resonance", 16, 71),
                //Sidechain
                MidiHandler("synth 1 source", 16, NrpnValue(2, 55).value(), range = Range(0, 4), controlType = MidiControlType.NRPN),
                MidiHandler("synth 1 attack", 16, NrpnValue(2, 56).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth 1 hold", 16, NrpnValue(2, 57).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth 1 decay", 16, NrpnValue(2, 58).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth 1 depth", 16, NrpnValue(2, 59).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth 2 source", 16, NrpnValue(2, 65).value(), range = Range(0, 4), controlType = MidiControlType.NRPN),
                MidiHandler("synth 2 attack", 16, NrpnValue(2, 66).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth 2 hold", 16, NrpnValue(2, 67).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth 2 decay", 16, NrpnValue(2, 68).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth 2 depth", 16, NrpnValue(1, 69).value(), controlType = MidiControlType.NRPN),
                //Mixer
                MidiHandler("synth 1 level", 16, 12),
                MidiHandler("synth 2 level", 16, 14),
                MidiHandler("synth 1 pan", 16, 117),
                MidiHandler("synth 2 pan", 16, 118),
                //Additional Controls
                MidiHandler("FX Bypass", 16, NrpnValue(1, 21).value(), range = Range(0, 1), controlType = MidiControlType.NRPN)
        ))
    }

    private fun synth(number: Int): List<MidiHandler> {
        return listOf(
                //Voice
                MidiHandler("synth $number Polyphony Mode", number, 3, range = Range(0, 2)),
                MidiHandler("synth $number Portamento Rate", number, 5),
                MidiHandler("synth $number Pre-Glide", number, 9, range = Range(52, 76)),
                MidiHandler("synth $number Keyboard Octave", number, 13, range = Range(58, 69)),
                //Oscillator
                MidiHandler("synth $number osc 1 wave", number, 19, range = Range(0, 29)),
                MidiHandler("synth $number osc 1 wave interpolate", number, 20),
                MidiHandler("synth $number osc 1 pulse width index", number, 21),
                MidiHandler("synth $number osc 1 virtual sync depth", number, 22),
                MidiHandler("synth $number osc 1 density", number, 24),
                MidiHandler("synth $number osc 1 density detune", number, 25),
                MidiHandler("synth $number osc 1 semitones", number, 26),
                MidiHandler("synth $number osc 1 cents", number, 27),
                MidiHandler("synth $number osc 1 pitchbend", number, 28, range = Range(52, 76)),
                MidiHandler("synth $number osc 2 wave", number, 29, range = Range(0, 29)),
                MidiHandler("synth $number osc 2 wave interpolate", number, 30),
                MidiHandler("synth $number osc 2 pulse width index", number, 31),
                MidiHandler("synth $number osc 2 virtual sync depth", number, 33),
                MidiHandler("synth $number osc 2 density", number, 35),
                MidiHandler("synth $number osc 2 density detune", number, 36),
                MidiHandler("synth $number osc 2 semitones", number, 37),
                MidiHandler("synth $number osc 2 cents", number, 39),
                MidiHandler("synth $number osc 2 pitchbend", number, 40, range = Range(52, 76)),
                //Mixer
                MidiHandler("synth $number osc 1 level", number, 51),
                MidiHandler("synth $number osc 2 level", number, 52),
                MidiHandler("synth $number ring mod level", number, 54),
                MidiHandler("synth $number noise level", number, 56),
                MidiHandler("synth $number pre FX level", number, 58, range = Range(52, 82)),
                MidiHandler("synth $number post FX level", number, 59, range = Range(52, 82)),
                //Filter
                MidiHandler("synth $number routing", number, 60, range = Range(0, 2)),
                MidiHandler("synth $number drive", number, 63),
                MidiHandler("synth $number drive type", number, 65, range = Range(0, 6)),
                MidiHandler("synth $number type", number, 68, range = Range(0, 5)),
                MidiHandler("synth $number frequency", number, 74),
                MidiHandler("synth $number tracking", number, 69),
                MidiHandler("synth $number resonance", number, 71),
                MidiHandler("synth $number Q normalize", number, 78),
                MidiHandler("synth $number env 2 to frequency", number, 79),
                //Envelope
                MidiHandler("synth $number env 1 velocity", number, 108),
                MidiHandler("synth $number env 1 attack", number, 73),
                MidiHandler("synth $number env 1 decay", number, 75),
                MidiHandler("synth $number env 1 sustain", number, 70),
                MidiHandler("synth $number env 1 release", number, 72),
                MidiHandler("synth $number env 2 velocity", number, NrpnValue(0, 0).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number env 2 attack", number, NrpnValue(0, 1).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number env 2 decay", number, NrpnValue(0, 2).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number env 2 sustain", number, NrpnValue(0, 3).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number env 2 release", number, NrpnValue(0, 4).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number env 3 delay", number, NrpnValue(0, 14).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number env 3 attack", number, NrpnValue(0, 15).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number env 3 decay", number, NrpnValue(0, 16).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number env 3 sustain", number, NrpnValue(0, 17).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number env 3 release", number, NrpnValue(0, 18).value(), controlType = MidiControlType.NRPN),
                //LFO
                MidiHandler("synth $number lfo 1 waveform", number, NrpnValue(0, 70).value(), range = Range(0, 37), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 1 phase offset", number, NrpnValue(0, 71).value(), range = Range(0, 119), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 1 slew rate", number, NrpnValue(0, 72).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 1 delay", number, NrpnValue(0, 74).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 1 delay sync", number, NrpnValue(0, 75).value(), range = Range(0, 35), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 1 rate", number, NrpnValue(0, 76).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 1 rate sync", number, NrpnValue(0, 77).value(), range = Range(0, 35), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 1 one shot", number, NrpnValue(0, 122).value(), range = Range(12, 13), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 1 key sync", number, NrpnValue(0, 122).value(), range = Range(14, 15), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 1 common sync", number, NrpnValue(0, 122).value(), range = Range(16, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 1 delay trigger", number, NrpnValue(0, 122).value(), range = Range(18, 19), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 1 fade mode", number, NrpnValue(0, 123).value(), range = Range(0, 3), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 2 waveform", number, NrpnValue(0, 79).value(), range = Range(0, 37), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 2 phase offset", number, NrpnValue(0, 80).value(), range = Range(0, 119), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 2 slew rate", number, NrpnValue(0, 81).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 2 delay", number, NrpnValue(0, 83).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 2 delay sync", number, NrpnValue(0, 84).value(), range = Range(0, 35), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 2 rate", number, NrpnValue(0, 85).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 2 rate sync", number, NrpnValue(0, 86).value(), range = Range(0, 35), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 2 one shot", number, NrpnValue(0, 122).value(), range = Range(22, 23), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 2 key sync", number, NrpnValue(0, 122).value(), range = Range(24, 25), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 2 common sync", number, NrpnValue(0, 122).value(), range = Range(26, 27), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 2 delay trigger", number, NrpnValue(0, 122).value(), range = Range(28, 29), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number lfo 2 fade mode", number, NrpnValue(0, 123).value(), range = Range(4, 7), controlType = MidiControlType.NRPN),
                //Effects and EQ
                MidiHandler("synth $number distortion level", number, 91),
                MidiHandler("synth $number chorus level", number, 93),
                MidiHandler("synth $number EQ bass frequency", number, NrpnValue(0, 104).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number EQ bass level", number, NrpnValue(0, 105).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number EQ mid frequency", number, NrpnValue(0, 106).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number EQ mid level", number, NrpnValue(0, 107).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number EQ treble frequency", number, NrpnValue(0, 108).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number EQ treble level", number, NrpnValue(0, 109).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number distortion type", number, NrpnValue(1, 0).value(), range = Range(0, 6), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number distortion compensation", number, NrpnValue(1, 1).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number chorus type", number, NrpnValue(1, 24).value(), range = Range(0, 1), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number chorus rate", number, NrpnValue(1, 25).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number chorus rate sync", number, NrpnValue(1, 26).value(), range = Range(0, 35), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number chorus feedback", number, NrpnValue(1, 27).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number chorus mod depth", number, NrpnValue(1, 28).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number chorus delay", number, NrpnValue(1, 29).value(), controlType = MidiControlType.NRPN),
                //Mod Matrix
                MidiHandler("synth $number mod matrix 1 source 1", number, NrpnValue(1, 83).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 1 source 2", number, NrpnValue(1, 84).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 1 depth", number, NrpnValue(1, 86).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 1 destination", number, NrpnValue(1, 87).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 2 source 1", number, NrpnValue(1, 88).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 2 source 2", number, NrpnValue(1, 89).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 2 depth", number, NrpnValue(1, 91).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 2 destination", number, NrpnValue(1, 92).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 3 source 1", number, NrpnValue(1, 93).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 3 source 2", number, NrpnValue(1, 94).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 3 depth", number, NrpnValue(1, 96).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 3 destination", number, NrpnValue(1, 97).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 4 source 1", number, NrpnValue(1, 98).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 4 source 2", number, NrpnValue(1, 99).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 4 depth", number, NrpnValue(1, 101).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 4 destination", number, NrpnValue(1, 102).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 5 source 1", number, NrpnValue(1, 103).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 5 source 2", number, NrpnValue(1, 104).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 5 depth", number, NrpnValue(1, 106).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 5 destination", number, NrpnValue(1, 107).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 6 source 1", number, NrpnValue(1, 108).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 6 source 2", number, NrpnValue(1, 109).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 6 depth", number, NrpnValue(1, 111).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 6 destination", number, NrpnValue(1, 112).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 7 source 1", number, NrpnValue(1, 113).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 7 source 2", number, NrpnValue(1, 114).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 7 depth", number, NrpnValue(1, 116).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 7 destination", number, NrpnValue(1, 117).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 8 source 1", number, NrpnValue(1, 118).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 8 source 2", number, NrpnValue(1, 119).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 8 depth", number, NrpnValue(1, 121).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 8 destination", number, NrpnValue(1, 122).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 9 source 1", number, NrpnValue(1, 123).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 9 source 2", number, NrpnValue(1, 124).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 9 depth", number, NrpnValue(1, 126).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 9 destination", number, NrpnValue(1, 127).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 10 source 1", number, NrpnValue(2, 0).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 10 source 2", number, NrpnValue(2, 1).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 10 depth", number, NrpnValue(2, 3).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 10 destination", number, NrpnValue(2, 4).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 11 source 1", number, NrpnValue(2, 5).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 11 source 2", number, NrpnValue(2, 6).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 11 depth", number, NrpnValue(2, 8).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 11 destination", number, NrpnValue(2, 9).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 12 source 1", number, NrpnValue(2, 10).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 12 source 2", number, NrpnValue(2, 11).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 12 depth", number, NrpnValue(2, 13).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 12 destination", number, NrpnValue(2, 14).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 13 source 1", number, NrpnValue(2, 15).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 13 source 2", number, NrpnValue(2, 16).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 13 depth", number, NrpnValue(2, 18).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 13 destination", number, NrpnValue(2, 19).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 14 source 1", number, NrpnValue(2, 20).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 14 source 2", number, NrpnValue(2, 21).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 14 depth", number, NrpnValue(2, 23).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 14 destination", number, NrpnValue(2, 24).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 15 source 1", number, NrpnValue(2, 25).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 15 source 2", number, NrpnValue(2, 27).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 15 depth", number, NrpnValue(2, 28).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 15 destination", number, NrpnValue(2, 29).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 16 source 1", number, NrpnValue(2, 30).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 16 source 2", number, NrpnValue(2, 32).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 16 depth", number, NrpnValue(2, 33).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 16 destination", number, NrpnValue(2, 34).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 17 source 1", number, NrpnValue(2, 35).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 17 source 2", number, NrpnValue(2, 37).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 17 depth", number, NrpnValue(2, 38).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 17 destination", number, NrpnValue(2, 39).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 18 source 1", number, NrpnValue(2, 40).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 18 source 2", number, NrpnValue(2, 42).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 18 depth", number, NrpnValue(2, 43).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 18 destination", number, NrpnValue(2, 44).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 19 source 1", number, NrpnValue(2, 45).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 19 source 2", number, NrpnValue(2, 47).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 19 depth", number, NrpnValue(2, 48).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 19 destination", number, NrpnValue(2, 49).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 20 source 1", number, NrpnValue(2, 50).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 20 source 2", number, NrpnValue(2, 52).value(), range = Range(0, 12), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 20 depth", number, NrpnValue(2, 53).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number mod matrix 20 destination", number, NrpnValue(2, 54).value(), range = Range(0, 17), controlType = MidiControlType.NRPN),
                //Macro Knob
                MidiHandler("synth $number macro knob 1 position", number, 80),
                MidiHandler("synth $number macro knob 1 destination A", number, NrpnValue(3, 0).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 start position A", number, NrpnValue(3, 1).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 end position A", number, NrpnValue(3, 2).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 depth A", number, NrpnValue(3, 3).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 destination B", number, NrpnValue(3, 4).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 start position B", number, NrpnValue(3, 5).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 end position B", number, NrpnValue(3, 6).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 depth B", number, NrpnValue(3, 7).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 destination C", number, NrpnValue(3, 8).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 start position C", number, NrpnValue(3, 9).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 end position C", number, NrpnValue(3, 10).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 depth C", number, NrpnValue(3, 11).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 destination D", number, NrpnValue(3, 12).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 start position D", number, NrpnValue(3, 13).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 end position D", number, NrpnValue(3, 14).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 1 depth D", number, NrpnValue(3, 15).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 position", number, 81),
                MidiHandler("synth $number macro knob 2 destination A", number, NrpnValue(3, 16).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 start position A", number, NrpnValue(3, 17).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 end position A", number, NrpnValue(3, 18).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 depth A", number, NrpnValue(3, 19).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 destination B", number, NrpnValue(3, 20).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 start position B", number, NrpnValue(3, 21).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 end position B", number, NrpnValue(3, 22).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 depth B", number, NrpnValue(3, 23).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 destination C", number, NrpnValue(3, 24).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 start position C", number, NrpnValue(3, 25).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 end position C", number, NrpnValue(3, 26).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 depth C", number, NrpnValue(3, 27).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 destination D", number, NrpnValue(3, 28).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 start position D", number, NrpnValue(3, 29).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 end position D", number, NrpnValue(3, 30).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 2 depth D", number, NrpnValue(3, 31).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 position", number, 82),
                MidiHandler("synth $number macro knob 3 destination A", number, NrpnValue(3, 32).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 start position A", number, NrpnValue(3, 33).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 end position A", number, NrpnValue(3, 34).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 depth A", number, NrpnValue(3, 35).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 destination B", number, NrpnValue(3, 36).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 start position B", number, NrpnValue(3, 37).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 end position B", number, NrpnValue(3, 38).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 depth B", number, NrpnValue(3, 39).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 destination C", number, NrpnValue(3, 40).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 start position C", number, NrpnValue(3, 41).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 end position C", number, NrpnValue(3, 42).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 depth C", number, NrpnValue(3, 43).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 destination D", number, NrpnValue(3, 44).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 start position D", number, NrpnValue(3, 45).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 end position D", number, NrpnValue(3, 46).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 3 depth D", number, NrpnValue(3, 47).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 position", number, 83),
                MidiHandler("synth $number macro knob 4 destination A", number, NrpnValue(3, 48).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 start position A", number, NrpnValue(3, 49).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 end position A", number, NrpnValue(3, 50).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 depth A", number, NrpnValue(3, 51).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 destination B", number, NrpnValue(3, 52).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 start position B", number, NrpnValue(3, 53).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 end position B", number, NrpnValue(3, 54).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 depth B", number, NrpnValue(3, 55).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 destination C", number, NrpnValue(3, 56).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 start position C", number, NrpnValue(3, 57).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 end position C", number, NrpnValue(3, 58).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 depth C", number, NrpnValue(3, 59).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 destination D", number, NrpnValue(3, 60).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 start position D", number, NrpnValue(3, 61).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 end position D", number, NrpnValue(3, 62).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 4 depth D", number, NrpnValue(3, 63).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 position", number, 84),
                MidiHandler("synth $number macro knob 5 destination A", number, NrpnValue(3, 64).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 start position A", number, NrpnValue(3, 65).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 end position A", number, NrpnValue(3, 66).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 depth A", number, NrpnValue(3, 67).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 destination B", number, NrpnValue(3, 68).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 start position B", number, NrpnValue(3, 69).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 end position B", number, NrpnValue(3, 70).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 depth B", number, NrpnValue(3, 71).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 destination C", number, NrpnValue(3, 72).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 start position C", number, NrpnValue(3, 73).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 end position C", number, NrpnValue(3, 74).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 depth C", number, NrpnValue(3, 75).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 destination D", number, NrpnValue(3, 76).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 start position D", number, NrpnValue(3, 77).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 end position D", number, NrpnValue(3, 78).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 5 depth D", number, NrpnValue(3, 79).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 position", number, 85),
                MidiHandler("synth $number macro knob 6 destination A", number, NrpnValue(3, 80).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 start position A", number, NrpnValue(3, 81).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 end position A", number, NrpnValue(3, 82).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 depth A", number, NrpnValue(3, 83).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 destination B", number, NrpnValue(3, 84).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 start position B", number, NrpnValue(3, 85).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 end position B", number, NrpnValue(3, 86).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 depth B", number, NrpnValue(3, 87).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 destination C", number, NrpnValue(3, 88).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 start position C", number, NrpnValue(3, 89).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 end position C", number, NrpnValue(3, 90).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 depth C", number, NrpnValue(3, 91).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 destination D", number, NrpnValue(3, 92).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 start position D", number, NrpnValue(3, 93).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 end position D", number, NrpnValue(3, 94).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 6 depth D", number, NrpnValue(3, 95).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 position", number, 86),
                MidiHandler("synth $number macro knob 7 destination A", number, NrpnValue(3, 96).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 start position A", number, NrpnValue(3, 97).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 end position A", number, NrpnValue(3, 98).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 depth A", number, NrpnValue(3, 99).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 destination B", number, NrpnValue(3, 100).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 start position B", number, NrpnValue(3, 101).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 end position B", number, NrpnValue(3, 102).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 depth B", number, NrpnValue(3, 103).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 destination C", number, NrpnValue(3, 104).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 start position C", number, NrpnValue(3, 105).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 end position C", number, NrpnValue(3, 106).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 depth C", number, NrpnValue(3, 107).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 destination D", number, NrpnValue(3, 108).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 start position D", number, NrpnValue(3, 109).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 end position D", number, NrpnValue(3, 110).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 7 depth D", number, NrpnValue(3, 111).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 position", number, 87),
                MidiHandler("synth $number macro knob 8 destination A", number, NrpnValue(3, 112).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 start position A", number, NrpnValue(3, 113).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 end position A", number, NrpnValue(3, 114).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 depth A", number, NrpnValue(3, 115).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 destination B", number, NrpnValue(3, 116).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8    start    position    B", number, NrpnValue(3, 117).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 end position B", number, NrpnValue(3, 118).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 depth B", number, NrpnValue(3, 119).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 destination C", number, NrpnValue(3, 120).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 start position C", number, NrpnValue(3, 121).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 end position C", number, NrpnValue(3, 122).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 depth C", number, NrpnValue(3, 123).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 destination D", number, NrpnValue(3, 124).value(), range = Range(0, 70), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 start position D", number, NrpnValue(3, 125).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 end position D", number, NrpnValue(3, 126).value(), controlType = MidiControlType.NRPN),
                MidiHandler("synth $number macro knob 8 depth D", number, NrpnValue(3, 127).value(), controlType = MidiControlType.NRPN)
        )
    }
}

class SynthMidiController(
        private val controls: List<MidiHandler>,
        val sendMessage: (ByteArray) -> Unit = {},
        val buffer: ByteArray = ByteArray(3)) {
    init {
        controls.forEach { it.byteBuffer = buffer; it.sendMessage = sendMessage }
    }

    fun control(name: String): MidiHandler {
        return controls.first { it.name == name }
    }
}





